[package]
name = "light-wallpaper"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "light_wallpaper_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"



anyhow = "1.0.102"
bitflags = "2.11.0"
cgmath = "0.18.0"
log = "0.4.29"

tempfile = "3.27.0"
thiserror = "2.0.18"

#vulkan
vulkanalia = {version="0.35.0", features = ["libloading", "window"] }
image = "0.25.10"

# wayland-shell
wayland-backend = "0.3.14"
wayland-client = "0.31.13"
wayland-protocols = "0.32.11"
wayland-scanner = "0.31.9"
winit = { version = "0.30.13", features = ["wayland"] }

# audio
rodio = "0.22.2"


# config
shellexpand = "3.1.2"
config = "0.15.23"
dirs = "6.0.0"
